GTowerLangush.AddLang( 1, "English")

GTowerLangush.AddWord( 1, "Inventory",	"Inventory")

GTowerLangush.AddWord( 1, "yes",	"Yes")
GTowerLangush.AddWord( 1, "no",		"No")
GTowerLangush.AddWord( 1, "upgrade",		"Upgrade {1}")
GTowerLangush.AddWord( 1, "unknown",	"Unknown")
GTowerLangush.AddWord( 1, "accept",	"Accept")
GTowerLangush.AddWord( 1, "decline",	"Decline")
GTowerLangush.AddWord( 1, "closeall",	"Close All")
GTowerLangush.AddWord( 1, "checkout",	"Checkout")
GTowerLangush.AddWord( 1, "cleanup",	"Clean Up")
GTowerLangush.AddWord( 1, "cancel",	"Cancel")

GTowerLangush.AddWord( 1, "bye",	"Bye")

GTowerLangush.AddWord( 1, "PleaseFullGtowerPack",	"Please get the latest GMod Tower modules at http://www.gmodtower.org/index.php?p=downloads")

GTowerLangush.AddWord( 1, "empty_bottle",		"Empty Bottle")
GTowerLangush.AddWord( 1, "empty_bottle_desc",		"Contains absolutely nothing.  Or does it?  You can't be sure until you break it open.")
GTowerLangush.AddWord( 1, "alcohol_bottle",		"Bottle of Alcohol")
GTowerLangush.AddWord( 1, "alcohol_bottle_desc",	"This bottle contains alcohol. Handle with care.")

GTowerLangush.AddWord( 1, "send_trade_request",		"Your trade request has been sent to {1}.")
GTowerLangush.AddWord( 1, "send_trade_recive",		"{1} wants to trade with you.")
GTowerLangush.AddWord( 1, "send_trade_declined",	"{1} has declined your trade.")
GTowerLangush.AddWord( 1, "send_trade_timeout",		"{1} did not respond to your trade.")
GTowerLangush.AddWord( 1, "trade_friend_accept",	"{1}'s acceptance.")

GTowerLangush.AddWord( 1, "send_trade_cancel",	"{1} has cancelled the trade.")
GTowerLangush.AddWord( 1, "trade_succeful",	"Trade successful.")

GTowerLangush.AddWord( 1, "trade_you_space",	"You do not have enough space in your inventory - trade failed." )
GTowerLangush.AddWord( 1, "trade_him_space",	"{1} does not have enough space in their inventory - trade failed.")


GTowerLangush.AddWord( 1, "trade_has_accepted",		"{1} accepted." )
GTowerLangush.AddWord( 1, "trade_hasnot_accepted" ,	"{1} has not accepted.")
GTowerLangush.AddWord( 1, "trade_trading_with" ,	"Trading with {1}...")
GTowerLangush.AddWord( 1, "trade_alredy_trading",	"{1} is currently trading." )
GTowerLangush.AddWord( 1, "trade_IamAlredyTrading",	"You are currently trading." )


GTowerLangush.AddWord( 1, "trade_denied",	"Trading is not allowed here.")
GTowerLangush.AddWord( 1, "not_enough_money",	"You do not have enough money.")

GTowerLangush.AddWord( 1, "Playerlist",	"Players List")

GTowerLangush.AddWord( 1, "vacant",		"Vacant")
GTowerLangush.AddWord( 1, "RoomRoomsAvailable",	"Greetings, {1}.  There are currently <font=Gtowerbigbold>{2}</font> available suite(s).   Do you wish to check-in?")
GTowerLangush.AddWord( 1, "RoomNotAvailable",	"Greetings, {1}.  We're sorry, there are no available suites at this time.  Please come back later.")
GTowerLangush.AddWord( 1, "RoomWait",		"Please wait while I setup your suite.")

GTowerLangush.AddWord( 1, "RoomLongAway",	"You have been away from your suite for {1} minute(s). You have been checked-out.")

GTowerLangush.AddWord( 1, "RoomGet",		"Thank you for staying at GMod Tower.\nI will assign you suite <font=Gtowerbigbold><color=white>#{1}</color></font>.\nIf you need any assistance with your suite, please contact local administrators or moderators.  Talk to me when you wish to check-out.")
GTowerLangush.AddWord( 1, "RoomGetSmall",	"You have been assigned to suite #{1}.")
GTowerLangush.AddWord( 1, "RoomDeny",		"Alright.  Please come back later.")

GTowerLangush.AddWord( 1, "RoomReturn",		"Hello again, {1}.  Would you like to check-out?")
GTowerLangush.AddWord( 1, "RoomReturnYes",	"I hope you enjoyed your stay at GMod Tower.  Please come back later.")
GTowerLangush.AddWord( 1, "RoomReturnNo",	"Alright.  I'm glad you're enjoying your suite.  Please talk to me when you wish to check-out.")
GTowerLangush.AddWord( 1, "RoomCleanUp",	"This will reset the suite to its original form.  All purchased furniture items will be deposited in the trunk.")

GTowerLangush.AddWord( 1, "RoomUpgrade",		"Upgrade your suite.")
GTowerLangush.AddWord( 1, "RoomDoWantUpgrade",		"Do you wish to upgrade {1} to level {2}?")
GTowerLangush.AddWord( 1, "RoomNotEnoughMoney",		"You do not have enough money to upgrade {1}.")
GTowerLangush.AddWord( 1, "RoomInventoryOwnRoom",	"You are only allowed to use this in your own suite.")
GTowerLangush.AddWord( 1, "RoomKickPlayers",	"Kick Players")

GTowerLangush.AddWord( 1, "RoomNotOwner",	"This is not your suite.")
GTowerLangush.AddWord( 1, "RoomCheckedOut",	"You have been checked out of your suite.")
GTowerLangush.AddWord( 1, "RoomAdminDisabled",	"Admins have disabled your ability to have a suite.")
GTowerLangush.AddWord( 1, "RoomAdminRemoved",	"An admin has removed you from your suite.")
GTowerLangush.AddWord( 1, "RoomMaxEnts",	"You can not have more than {1} entities in your suite.")

GTowerLangush.AddWord( 1, "RoomOwnerBroke",		"You aren't the suite owner or GTowerRooms broke.")
GTowerLangush.AddWord( 1, "RoomRadioWrongID",	"Radio's suite ID is {1}.  You have {2}.")

GTowerLangush.AddWord( 1, "Scoreboard_awards",		"Awards")

GTowerLangush.AddWord( 1, "Group_menu",			"Group")
GTowerLangush.AddWord( 1, "Group_makeowner",		"Set as Group Leader")
GTowerLangush.AddWord( 1, "Group_removegroup",		"Kick from Group")
GTowerLangush.AddWord( 1, "Group_inviteroup",		"Invite to Group")
GTowerLangush.AddWord( 1, "Group_newownermakesure",	"Are you sure you want to set {1} as the group leader?")
GTowerLangush.AddWord( 1, "Group_younewowner",		"You are now the leader of the group.")
GTowerLangush.AddWord( 1, "Group_himnewowner",		"{1} is now the leader of the group.")

GTowerLangush.AddWord( 1, "GroupInvite",		"{1} has invited you to their group.")
GTowerLangush.AddWord( 1, "GroupDeny",		"{1} has denied your request.")
GTowerLangush.AddWord( 1, "Group_target_no_group",	"{1} is no longer in a group.")
GTowerLangush.AddWord( 1, "Group_full",			"The group is full.")
GTowerLangush.AddWord( 1, "Group_already_in_group",	"You are already in a group.")
GTowerLangush.AddWord( 1, "Group_he_already_in_group",	"{1} is already in a group.")
GTowerLangush.AddWord( 1, "Group_invite_send",		"You have asked {1} to join your group.")
GTowerLangush.AddWord( 1, "Group_leave",		"Leave Group")
GTowerLangush.AddWord( 1, "Group_leavesure",		"Are you sure you want to leave your group?")


GTowerLangush.AddWord( 1, "Group_setting_sizename",		"Size of group health bars.")
GTowerLangush.AddWord( 1, "Group_setting_bordername",		"Distance between each group members' name.")
GTowerLangush.AddWord( 1, "Group_setting_alignname",		"List group vertically.")
GTowerLangush.AddWord( 1, "Group_setting_positionname",		"Posistion of group list.")
GTowerLangush.AddWord( 1, "Group_setting_avatarsizename",	"Group member avatar size.")
GTowerLangush.AddWord( 1, "Group_setting_allbordername",	"Distance from edge of screen.")


GTowerLangush.AddWord( 1, "gui_setting_name",		"Health/Ammo Bar")
GTowerLangush.AddWord( 1, "gui_setting_ammosize",	"Ammo bar size.")
GTowerLangush.AddWord( 1, "gui_setting_ammox",		"Ammo horizontal offset.")
GTowerLangush.AddWord( 1, "gui_setting_ammoy",		"Ammo vertical offset.")
GTowerLangush.AddWord( 1, "gui_setting_healthx",	"Health hortizontal offset.")
GTowerLangush.AddWord( 1, "gui_setting_healthy",	"Health vertical offset.")
GTowerLangush.AddWord( 1, "gui_setting_chatwidth",	"Chat box width.")
GTowerLangush.AddWord( 1, "gui_setting_instant",	"Instant GUI animation transitions.")

GTowerLangush.AddWord( 1, "RadioTurnedOff",		"Radio Off")
GTowerLangush.AddWord( 1, "RadioPlaying",		"Playing")
GTowerLangush.AddWord( 1, "RadioLoading",		"Loading...")
GTowerLangush.AddWord( 1, "RadioUnsupportedFormat",	"Stream using bad format.")
GTowerLangush.AddWord( 1, "RadioTimeout",		"Stream timed out.")
GTowerLangush.AddWord( 1, "RadioBASSInitError",		"BASS initialization error; reconnect.")
GTowerLangush.AddWord( 1, "RadioUnknown",		"Stream gave unknown error.")

GTowerLangush.AddWord( 1, "JukeBoxTurnedOff",		"Jukebox Off (5 GMC per choice)")
GTowerLangush.AddWord( 1, "JukeBoxNotEnoughMoney",	"You cannot afford to change the jukebox.")

GTowerLangush.AddWord( 1, "MenuReportAdmin",	"Report to Admin")
GTowerLangush.AddWord( 1, "MenuInformation",	"Information")
GTowerLangush.AddWord( 1, "MenuTrade",		"Trade")

GTowerLangush.AddWord( 1, "StoreNoSlots",	"You do not have enough inventory slots.")
GTowerLangush.AddWord( 1, "StoreNotEnoughMoney",	"You cannot afford this item.")
GTowerLangush.AddWord( 1, "StorePurchased",	"You've just bought ''{1}''.")
GTowerLangush.AddWord( 1, "StoreConfirmUpgrade",	"Are you sure you want to upgrade the ''{1}'' for {2} GMC?")
GTowerLangush.AddWord( 1, "StoreConfirmPurchase",	"Are you sure you want to buy ''{1}'' for {2} GMC?")

GTowerLangush.AddWord( 1, "BankFull",	"There isn't enough space in your bank.")
GTowerLangush.AddWord( 1, "InventoryTooFar",	"It's too far away.")

GTowerLangush.AddWord( 1, "BackpackShouldEquip",	"You should equip backpack before using it.")

GTowerLangush.AddWord( 1, "AchievementsGot",	"Congratulations! You've just achieved: {1}.")
GTowerLangush.AddWord( 1, "AchievementsTrophyGot",	"You got the {1}.")
GTowerLangush.AddWord( 1, "AchievementsTrophyFailed",	"Oops, a mistake was made.")

GTowerLangush.AddWord( 1, "MoneyEarned",	"You've earned {1} GMC.")
GTowerLangush.AddWord( 1, "MoneySpent",	"You've spent {1} GMC.")

GTowerLangush.AddWord( 1, "GamemodeFull",	"Sorry, {1} is full.")

GTowerLangush.AddWord( 1, "AdminNot",	"You are not an admin!")
GTowerLangush.AddWord( 1, "AfkTimer",	"AFK TIMER: {1} seconds.")

GTowerLangush.AddWord( 1, "PlayerModel",	"Player Model")
GTowerLangush.AddWord( 1, "MissingTrophies",	"Missing Trophies?")
GTowerLangush.AddWord( 1, "Theater",	"Theater")

GTowerLangush.AddWord( 1, "EventMiniStart",	"Event System has started minigame: {1}.")
GTowerLangush.AddWord( 1, "EventMiniEnd",	"Event System has ended minigame: {1}.")
GTowerLangush.AddWord( 1, "EventSetSale",	"Event System has set the {1} on sale!")
GTowerLangush.AddWord( 1, "EventEndSale",	"Event System has ended the sale on the {1}.")
GTowerLangush.AddWord( 1, "EventError",		"Something is terribly wrong with event system! Tell an admin about this!")
GTowerLangush.AddWord( 1, "EventEndingTime", "Event will end in {1}!")
GTowerLangush.AddWord( 1, "EventNextEventTime", "Be ready, we have random events every half an hour!")
GTowerLangush.AddWord( 1, "EventNoEvent", "Sorry, there will be no event!")
GTowerLangush.AddWord( 1, "EventNeedMorePlayers", "Event skipped, need more players (10)!")
GTowerLangush.AddWord( 1, "EventAdminDisabled", "An admin ({1}) has disabled event system.")
GTowerLangush.AddWord( 1, "EventAdminEnabled", "An admin ({1}) has enabled event system.")
GTowerLangush.AddWord( 1, "EventAdminManual", "An admin ({1}) has forced event system.")

GTowerLangush.AddWord( 1, "AuctionStarted", "Auction started! Place a bet like this: !bet 5000")
GTowerLangush.AddWord( 1, "AuctionCurrentBet", "Current bet: {1} GMC by {2}")
GTowerLangush.AddWord( 1, "AuctionStartedItem", "New lot: {1}. Starting price: {2}. Please check if you have free space in inventory before joining.")
GTowerLangush.AddWord( 1, "AuctionSold", "{1} sold to {2} for {3} GMC!")
GTowerLangush.AddWord( 1, "AuctionEnded", "Auction ended!")
GTowerLangush.AddWord( 1, "AuctionNoInventorySpace", "{1} don't have space in inventory! He gets 50% of {2} price!")

GTowerLangush.AddWord( 1, "AdminMiniStart",	"An admin ({1}) has started minigame: {2}.")
GTowerLangush.AddWord( 1, "AdminMiniEnd",	"An admin ({1}) has ended minigame: {2}.")
GTowerLangush.AddWord( 1, "AdminClrDecals",	"An admin ({1}) has cleared all decals.")
GTowerLangush.AddWord( 1, "AdminClrSounds",	"An admin ({1}) has stopped all sounds.")
GTowerLangush.AddWord( 1, "AdminClrStreams", "An admin ({1}) has removed all streams.")
GTowerLangush.AddWord( 1, "AdminSetSale",	"An admin ({1}) has set the {2} on sale!")
GTowerLangush.AddWord( 1, "AdminEndSale",	"An admin ({1}) has ended the sale on the {2}.")
GTowerLangush.AddWord( 1, "AdminRagdoll",	"An admin or privadmin ({1}) has ragdolled you!")
GTowerLangush.AddWord( 1, "AdminRagdollA",	"You've ragdolled {1}!")
GTowerLangush.AddWord( 1, "AdminSetMoney",	"An admin ({1}) has set your money to {2}.")

GTowerLangush.AddWord( 1, "TODO", "TODO")
GTowerLangush.AddWord( 1, "Gamemode Ports", "Gamemode Ports" )
GTowerLangush.AddWord( 1, "Entertainment Plaza", "Entertainment Plaza")
GTowerLangush.AddWord( 1, "Suite Floor", "Suite Floor" )
GTowerLangush.AddWord( 1, "Suites 1-5", "Suites 1-5" )
GTowerLangush.AddWord( 1, "Suites 6-10", "Suites 6-10" )
GTowerLangush.AddWord( 1, "Arcade", "Arcade" )
GTowerLangush.AddWord( 1, "Teleporters", "Teleporters")
GTowerLangush.AddWord( 1, "Dev. HQ", "Dev. HQ" )
GTowerLangush.AddWord( 1, "Resturant", "Resturant")
GTowerLangush.AddWord( 1, "Ball Race", "Ball Race" )
GTowerLangush.AddWord( 1, "Action Genre", "Action Genre")
GTowerLangush.AddWord( 1, "PVP Battle", "PVP Battle" )
GTowerLangush.AddWord( 1, "Stealth - Coming Soon", "Stealth - Coming Soon" )
GTowerLangush.AddWord( 1, "Coming Soon", "Coming Soon" )
GTowerLangush.AddWord( 1, "GMT: Adventure", "GMT: Adventure" )
GTowerLangush.AddWord( 1, "Stealth", "Stealth" )
GTowerLangush.AddWord( 1, "Puzzle: Impossible", "Puzzle: Impossible" )
GTowerLangush.AddWord( 1, "Tetris", "Tetris" )
GTowerLangush.AddWord( 1, "Bar", "Bar" )
GTowerLangush.AddWord( 1, "Theatre", "Theatre" )
GTowerLangush.AddWord( 1, "Party Suite", "Party Suite" )
GTowerLangush.AddWord( 1, "The Gallery", "The Gallery" )
GTowerLangush.AddWord( 1, "Twist of the Mind", "Twist of the Mind" )
GTowerLangush.AddWord( 1, "Mini-Golf", "Mini-Golf" )
GTowerLangush.AddWord( 1, "Monotone", "Monotone" )
GTowerLangush.AddWord( 1, "Harvest", "Harvest") 
GTowerLangush.AddWord( 1, "Furniture Store", "Furniture Store" )
GTowerLangush.AddWord( 1, "Hat Store", "Hat Store" )
GTowerLangush.AddWord( 1, "Souvenir Store", "Souvenir Store" )
GTowerLangush.AddWord( 1, "Electronic Store", "Electronic Store" )
GTowerLangush.AddWord( 1, "Conquest", "Conquest" )
GTowerLangush.AddWord( 1, "Chainsaw Battle!","Chainsaw Battle!")
GTowerLangush.AddWord( 1, "Blizzard Storm!", "Blizzard Storm!" )
