GTowerLangush.AddLang( 2, "French")

GTowerLangush.AddWord( 2, "Inventory",	"Inventaire")

GTowerLangush.AddWord( 2, "yes",	"Oui")
GTowerLangush.AddWord( 2, "no",		"Non")
GTowerLangush.AddWord( 2, "upgrade",  "Upgrade {1}")
GTowerLangush.AddWord( 2, "unknown",	"Unknown")
GTowerLangush.AddWord( 2, "accept",	  "Accepter")
GTowerLangush.AddWord( 2, "decline",	"Refuser")
GTowerLangush.AddWord( 2, "closeall",	"Close All")
GTowerLangush.AddWord( 2, "checkout",	"Rendre les clés de la suite")
GTowerLangush.AddWord( 2, "cleanup",	"Clean Up")
GTowerLangush.AddWord( 2, "cancel",	"Annuler")

GTowerLangush.AddWord( 2, "bye",	"Au revoir")

GTowerLangush.AddWord( 2, "PleaseFullGtowerPack",	"Obtenez les dernières mises à jour du serveur http://francerp.fr")

GTowerLangush.AddWord( 2, "empty_bottle",		"Bouteille Vide")
GTowerLangush.AddWord( 2, "empty_bottle_desc",		"Ne contient absolument rien.  Ou peut être ? Vous ne pouvez pas être sûr avant de l'avoir ouvert.")
GTowerLangush.AddWord( 2, "alcohol_bottle",		"Bouteille d'alcool")
GTowerLangush.AddWord( 2, "alcohol_bottle_desc",	"Cette bouteille contient de l'alcool. Manipuler avec soin.")

GTowerLangush.AddWord( 2, "send_trade_request",		"Votre demande d'échange à été envoyée à {1}.")
GTowerLangush.AddWord( 2, "send_trade_recive",		"{1} veut échanger avec vous.")
GTowerLangush.AddWord( 2, "send_trade_declined",	"{1} a refusé votre échange.")
GTowerLangush.AddWord( 2, "send_trade_timeout",		"{1} n'a pas répondu à votre échange.")
GTowerLangush.AddWord( 2, "trade_friend_accept",	"{1} vient d'accepté.")

GTowerLangush.AddWord( 2, "send_trade_cancel",	"{1} a annulé le commerce.")
GTowerLangush.AddWord( 2, "trade_succeful",	"Echange effectué avec succès.")

GTowerLangush.AddWord( 2, "trade_you_space",	"Vous n'avez pas assez d'espace dans votre inventaire - l'échange à échoué." )
GTowerLangush.AddWord( 2, "trade_him_space",	"{1} n'a pas assez d'espace dans son inventaire - l'échange à échoué.")


GTowerLangush.AddWord( 2, "trade_has_accepted",		"{1} accepter." )
GTowerLangush.AddWord( 2, "trade_hasnot_accepted" ,	"{1} n'a pas accepté.")
GTowerLangush.AddWord( 2, "trade_trading_with" ,	"Echange avec {1}...")
GTowerLangush.AddWord( 2, "trade_alredy_trading",	"{1} échange déjà actuellement." )
GTowerLangush.AddWord( 2, "trade_IamAlredyTrading",	"Vous échanger actuellement." )


GTowerLangush.AddWord( 2, "trade_denied",	"L'échange n'est pas autorisé ici.")
GTowerLangush.AddWord( 2, "not_enough_money",	"Vous n'avez pas assez d'argent.")

GTowerLangush.AddWord( 2, "Playerlist",	"Liste Joueurs")

GTowerLangush.AddWord( 2, "vacant",		"Innocupé")
GTowerLangush.AddWord( 2, "RoomRoomsAvailable",	"Bienvenue, {1}.  Nous avons actuellement <font=Gtowerbigbold>{2}</font> suites de disponibles.   Voulez-vous en réservez une ?")
GTowerLangush.AddWord( 2, "RoomNotAvailable",	"Salutations, {1}.  Nous sommes désolés, il n'y a aucune suite de disponible actuellement. Revenez s'il vous plaît plus tard.")
GTowerLangush.AddWord( 2, "RoomWait",		"Veuillez patienter pendant la configuration de votre suite.")

GTowerLangush.AddWord( 2, "RoomLongAway",	"Vous étiez loin de votre suite pendant {1} minute(s). Vous avez été expulsé.")

GTowerLangush.AddWord( 2, "RoomGet",		"Merci d'avoir choisi notre hôtel.\nJe vous assigne la suite numéro <font=Gtowerbigbold><color=white>#{1}</color></font>.\nSi vous avez besoin d'une assistance avec votre suite, contactez s'il vous plaît un administrateur ou un modérateur. Parlez-moi quand vous voudrez partir de votre suite.")
GTowerLangush.AddWord( 2, "RoomGetSmall",	"Vous avez été assigné à la suite numéro #{1}.")
GTowerLangush.AddWord( 2, "RoomDeny",		"Bien. Merci de revenir plus tard.")

GTowerLangush.AddWord( 2, "RoomReturn",		"Bonjour, {1}, \nQue puis-je faire pour vous?")
GTowerLangush.AddWord( 2, "RoomReturnYes",	"J’espère que vous avez apprécié votre séjour à l'hôtel.  S’il vous plaît pensez à revenir plus tard.")
GTowerLangush.AddWord( 2, "RoomReturnNo",	"Bien.  Je suis heureux que vous aimiez votre suite.  Parlez-moi s'il vous plaît quand vous souhaitez partir.")
GTowerLangush.AddWord( 2, "RoomCleanUp",	"Cela réinitialisera la suite. Tous les articles de meubles achetés seront déposés dans votre coffre.")

GTowerLangush.AddWord( 2, "RoomUpgrade",		"Mettez à jour votre suite.")
GTowerLangush.AddWord( 2, "RoomDoWantUpgrade",		"Voulez-vous améliorer {1} au niveau {2}?")
GTowerLangush.AddWord( 2, "RoomNotEnoughMoney",		"Vous n'avez pas assez d'argent pour mettre à niveau {1}.")
GTowerLangush.AddWord( 2, "RoomInventoryOwnRoom",	"Vous êtes seulement autorisé à l'utiliser dans votre propre suite.")
GTowerLangush.AddWord( 2, "RoomKickPlayers",	"Expulser joueurs")

GTowerLangush.AddWord( 2, "RoomNotOwner",	"Ce n'est pas votre suite.")
GTowerLangush.AddWord( 2, "RoomCheckedOut",	"Vous avez été expulsé de votre suite.")
GTowerLangush.AddWord( 2, "RoomAdminDisabled",	"Les administrateurs ont désactivé votre capacité à avoir une suite.")
GTowerLangush.AddWord( 2, "RoomAdminRemoved",	"Un administrateur vous a retiré de votre suite.")
GTowerLangush.AddWord( 2, "RoomMaxEnts",	"Vous ne pouvez pas avoir plus de {1} entités dans votre suite..")

GTowerLangush.AddWord( 2, "RoomOwnerBroke",		"Vous n'êtes pas le propriétaire de la suite.")
GTowerLangush.AddWord( 2, "RoomRadioWrongID",	"L'iD de la radio est {1}.  Tu as {2}.")

GTowerLangush.AddWord( 2, "Scoreboard_awards",		"Succès")

GTowerLangush.AddWord( 2, "Group_menu",			"Group")
GTowerLangush.AddWord( 2, "Group_makeowner",		"Définir comme chef de groupe")
GTowerLangush.AddWord( 2, "Group_removegroup",		"Retirer du groupe")
GTowerLangush.AddWord( 2, "Group_inviteroup",		"Inviter au groupe")
GTowerLangush.AddWord( 2, "Group_newownermakesure",	"Êtes-vous sûr de vouloir définir {1} en tant que chef de groupe?")
GTowerLangush.AddWord( 2, "Group_younewowner",		"Vous êtes maintenant le chef du groupe.")
GTowerLangush.AddWord( 2, "Group_himnewowner",		"{1} est maintenant le leader du groupe.")

GTowerLangush.AddWord( 2, "GroupInvite",		"{1} vous a invité à son groupe.")
GTowerLangush.AddWord( 2, "GroupDeny",		"{1} a refusé votre demande.")
GTowerLangush.AddWord( 2, "Group_target_no_group",	"{1} n'est plus dans un groupe.")
GTowerLangush.AddWord( 2, "Group_full",			"Le groupe est complet.")
GTowerLangush.AddWord( 2, "Group_already_in_group",	"Vous êtes déjà dans un groupe.")
GTowerLangush.AddWord( 2, "Group_he_already_in_group",	"{1} est déjà dans un groupe.")
GTowerLangush.AddWord( 2, "Group_invite_send",		"Vous avez demandé à {1} de rejoindre votre groupe.")
GTowerLangush.AddWord( 2, "Group_leave",		"Quitter le groupe")
GTowerLangush.AddWord( 2, "Group_leavesure",		"Êtes-vous sûr de vouloir quitter votre groupe?")


GTowerLangush.AddWord( 2, "Group_setting_sizename",		"Taille des barres de santé du groupe.")
GTowerLangush.AddWord( 2, "Group_setting_bordername",		"Distance des membres du groupe.")
GTowerLangush.AddWord( 2, "Group_setting_alignname",		"Liste du groupe vertical.")
GTowerLangush.AddWord( 2, "Group_setting_positionname",		"Position de la liste de groupe.")
GTowerLangush.AddWord( 2, "Group_setting_avatarsizename",	"Taille de l'avatar du membre du groupe.")
GTowerLangush.AddWord( 2, "Group_setting_allbordername",	"Distance du bord de l'écran.")


GTowerLangush.AddWord( 2, "gui_setting_name",		"Barre de santé / munitions")
GTowerLangush.AddWord( 2, "gui_setting_ammosize",	"Taille de la barre de munitions.")
GTowerLangush.AddWord( 2, "gui_setting_ammox",		"Décalage horizontal des munitions.")
GTowerLangush.AddWord( 2, "gui_setting_ammoy",		"Décalage vertical des munitions.")
GTowerLangush.AddWord( 2, "gui_setting_healthx",	"Décalage hortizontal de santé.")
GTowerLangush.AddWord( 2, "gui_setting_healthy",	"Décalage vertical de la santé.")
GTowerLangush.AddWord( 2, "gui_setting_chatwidth",	"Grandeur du tchat.")
GTowerLangush.AddWord( 2, "gui_setting_instant",	"Transitions d'animation instantanée de l'interface graphique.")

GTowerLangush.AddWord( 2, "RadioTurnedOff",		"Radio coupée")
GTowerLangush.AddWord( 2, "RadioPlaying",		"Jouer")
GTowerLangush.AddWord( 2, "RadioLoading",		"Chargement...")
GTowerLangush.AddWord( 2, "RadioUnsupportedFormat",	"Mauvais format.")
GTowerLangush.AddWord( 2, "RadioTimeout",		"Le flux a expiré.")
GTowerLangush.AddWord( 2, "RadioBASSInitError",		"Erreur d'initialisation BASS; reconnecter.")
GTowerLangush.AddWord( 2, "RadioUnknown",		"Le flux à donné une erreur inconnue.")

GTowerLangush.AddWord( 2, "JukeBoxTurnedOff",		"Jukebox coupé (5 GMC par choix)")
GTowerLangush.AddWord( 2, "JukeBoxNotEnoughMoney",	"Vous ne pouvez pas vous permettre de changer le jukebox.")

GTowerLangush.AddWord( 2, "MenuReportAdmin",	"Rapporter à l'administrateur")
GTowerLangush.AddWord( 2, "MenuInformation",	"Information")
GTowerLangush.AddWord( 2, "MenuTrade",		"Echange")

GTowerLangush.AddWord( 2, "StoreNoSlots",	"Vous n'avez pas assez d'emplacements dans l'inventaire.")
GTowerLangush.AddWord( 2, "StoreNotEnoughMoney",	"Vous ne pouvez pas vous acheter cet objet.")
GTowerLangush.AddWord( 2, "StorePurchased",	"Vous venez d'acheter ''{1}''.")
GTowerLangush.AddWord( 2, "StoreConfirmUpgrade",	"Êtes-vous sûr de vouloir améliorer ''{1}'' pour {2} GMC?")
GTowerLangush.AddWord( 2, "StoreConfirmPurchase",	"Êtes-vous sûr de vouloir acheter ''{1}'' pour {2} GMC?")

GTowerLangush.AddWord( 2, "BankFull",	"Il n'y à pas assez d'espace dans votre banque.")
GTowerLangush.AddWord( 2, "InventoryTooFar",	"C'est trop loin.")

GTowerLangush.AddWord( 2, "BackpackShouldEquip",	"Vous devriez équiper le sac à dos avant de l'utiliser.")

GTowerLangush.AddWord( 2, "AchievementsGot",	"Toutes nos félicitations! Vous venez d'accomplir: {1}.")
GTowerLangush.AddWord( 2, "AchievementsTrophyGot",	"Vous avez le {1}.")
GTowerLangush.AddWord( 2, "AchievementsTrophyFailed",	"Oups, une erreur a été commise.")

GTowerLangush.AddWord( 2, "MoneyEarned",	"Tu as gagné {1} GMC.")
GTowerLangush.AddWord( 2, "MoneySpent",	"Vous avez dépensé {1} GMC.")

GTowerLangush.AddWord( 2, "GamemodeFull",	"Désoler, {1} est complet.")

GTowerLangush.AddWord( 2, "AdminNot",	"Vous n'êtes pas un administrateur!")
GTowerLangush.AddWord( 2, "AfkTimer",	"AFK TIMER: {1} secondes.")

GTowerLangush.AddWord( 2, "PlayerModel",	"Modèle de joueur")
GTowerLangush.AddWord( 2, "MissingTrophies",	"Trophées manquants?")
GTowerLangush.AddWord( 2, "Theater",	"Théâtre")

GTowerLangush.AddWord( 2, "EventMiniStart",	"Le serveur à démarré le mini-jeu: {1}.")
GTowerLangush.AddWord( 2, "EventMiniEnd",	"Le serveur à terminé le mini-jeu: {1}.")
GTowerLangush.AddWord( 2, "EventSetSale",	"Le serveur à défini le {1} en soldes!")
GTowerLangush.AddWord( 2, "EventEndSale",	"Le serveur à mis fin à la vente sur le {1}.")
GTowerLangush.AddWord( 2, "EventError",		"Quelque chose ne va pas avec le système d'événements! Parlez-en à un administrateur!")
GTowerLangush.AddWord( 2, "EventEndingTime", "L'événement se terminera par {1}!")
GTowerLangush.AddWord( 2, "EventNextEventTime", "Soyez prêt, nous avons des événements aléatoires toutes les demi-heures!")
GTowerLangush.AddWord( 2, "EventNoEvent", "Désolé, il n'y aura pas d'événement!")
GTowerLangush.AddWord( 2, "EventNeedMorePlayers", "Événement ignoré, besoin de plus de joueurs (10)!")
GTowerLangush.AddWord( 2, "EventAdminDisabled", "Un admin à ({1}) à désactivé le système d'événements.")
GTowerLangush.AddWord( 2, "EventAdminEnabled", "Un admin à ({1}) à activé le système d'événements.")
GTowerLangush.AddWord( 2, "EventAdminManual", "Un admin à ({1}) à forcé le système d'événement.")

GTowerLangush.AddWord( 2, "AuctionStarted", "Un pari à commencé! Placez un pari, en faisant: !bet MontantGMC")
GTowerLangush.AddWord( 2, "AuctionCurrentBet", "Pari actuel: {1} GMC par {2}")
GTowerLangush.AddWord( 2, "AuctionStartedItem", "Nouveau lot: {1}. Prix de départ: {2}. S'il vous plaît vérifier si vous avez de l'espace libre dans l'inventaire avant de rejoindre.")
GTowerLangush.AddWord( 2, "AuctionSold", "{1} vendu à {2} pour {3} GMC!")
GTowerLangush.AddWord( 2, "AuctionEnded", "Pari terminé!")
GTowerLangush.AddWord( 2, "AuctionNoInventorySpace", "{1} Pas de place dans l'inventaire! Il obtient 50% de {2} sur le prix!")

GTowerLangush.AddWord( 2, "AdminMiniStart",	"Un admin à ({1}) à commencé le mini-jeu: {2}.")
GTowerLangush.AddWord( 2, "AdminMiniEnd",	"Un admin à ({1}) à finis le mini-jeu: {2}.")
GTowerLangush.AddWord( 2, "AdminClrDecals",	"Un admin à ({1}) à effacé tous les autocollants.")
GTowerLangush.AddWord( 2, "AdminClrSounds",	"Un admin à ({1}) à stopper tout les sons.")
GTowerLangush.AddWord( 2, "AdminClrStreams", "Un admin à ({1}) à enlever tout les flux.")
GTowerLangush.AddWord( 2, "AdminSetSale",	"Un admin à ({1}) à met le {2} en solde!")
GTowerLangush.AddWord( 2, "AdminEndSale",	"Un admin à ({1}) à terminé la vente sur le {2}.")
GTowerLangush.AddWord( 2, "AdminRagdoll",	"Un admin à ({1}) vous à rendu tout mou !")
GTowerLangush.AddWord( 2, "AdminRagdollA",	"Vous avez ragdolled {1}!")
GTowerLangush.AddWord( 2, "AdminSetMoney",	"Un admin à ({1}) à mis votre argent à {2}.")

GTowerLangush.AddWord( 2, "TODO", "TODO")
GTowerLangush.AddWord( 2, "Gamemode Ports", "Gamemode Ports" )
GTowerLangush.AddWord( 2, "Entertainment Plaza", "Entertainment Plaza")
GTowerLangush.AddWord( 2, "Suite Floor", "Suite Floor" )
GTowerLangush.AddWord( 2, "Suites 1-5", "Suites 1-5" )
GTowerLangush.AddWord( 2, "Suites 6-10", "Suites 6-10" )
GTowerLangush.AddWord( 2, "Arcade", "Arcade" )
GTowerLangush.AddWord( 2, "Teleporters", "Teleporters")
GTowerLangush.AddWord( 2, "Dev. HQ", "Dev. HQ" )
GTowerLangush.AddWord( 2, "Resturant", "Resturant")
GTowerLangush.AddWord( 2, "Ball Race", "Ball Race" )
GTowerLangush.AddWord( 2, "Action Genre", "Action Genre")
GTowerLangush.AddWord( 2, "PVP Battle", "PVP Battle" )
GTowerLangush.AddWord( 2, "Stealth - Coming Soon", "Stealth - Coming Soon" )
GTowerLangush.AddWord( 2, "Coming Soon", "Coming Soon" )
GTowerLangush.AddWord( 2, "GMT: Adventure", "GMT: Adventure" )
GTowerLangush.AddWord( 2, "Stealth", "Stealth" )
GTowerLangush.AddWord( 2, "Puzzle: Impossible", "Puzzle: Impossible" )
GTowerLangush.AddWord( 2, "Tetris", "Tetris" )
GTowerLangush.AddWord( 2, "Bar", "Bar" )
GTowerLangush.AddWord( 2, "Theatre", "Theatre" )
GTowerLangush.AddWord( 2, "Party Suite", "Party Suite" )
GTowerLangush.AddWord( 2, "The Gallery", "The Gallery" )
GTowerLangush.AddWord( 2, "Twist of the Mind", "Twist of the Mind" )
GTowerLangush.AddWord( 2, "Mini-Golf", "Mini-Golf" )
GTowerLangush.AddWord( 2, "Monotone", "Monotone" )
GTowerLangush.AddWord( 2, "Harvest", "Harvest") 
GTowerLangush.AddWord( 2, "Furniture Store", "Furniture Store" )
GTowerLangush.AddWord( 2, "Hat Store", "Hat Store" )
GTowerLangush.AddWord( 2, "Souvenir Store", "Souvenir Store" )
GTowerLangush.AddWord( 2, "Electronic Store", "Electronic Store" )
GTowerLangush.AddWord( 2, "Conquest", "Conquest" )
GTowerLangush.AddWord( 2, "Chainsaw Battle!","Chainsaw Battle!")
GTowerLangush.AddWord( 2, "Blizzard Storm!", "Blizzard Storm!" )
