GTowerLangush.AddLang( 2, "French")

GTowerLangush.AddWord( 2, "Inventory",	"Inventaire")

GTowerLangush.AddWord( 2, "yes",	"Oui")
GTowerLangush.AddWord( 2, "no",		"Non")
GTowerLangush.AddWord( 2, "upgrade",  "Upgrade {1}")
GTowerLangush.AddWord( 2, "unknown",	"Unknown")
GTowerLangush.AddWord( 2, "accept",	  "Accepter")
GTowerLangush.AddWord( 2, "decline",	"Refuser")
GTowerLangush.AddWord( 2, "closeall",	"Close All")
GTowerLangush.AddWord( 2, "checkout",	"Rendre les clés de la suite")
GTowerLangush.AddWord( 2, "cleanup",	"Clean Up")
GTowerLangush.AddWord( 2, "cancel",	"Annuler")

GTowerLangush.AddWord( 2, "bye",	"Au revoir")

GTowerLangush.AddWord( 2, "PleaseFullGtowerPack",	"Please get the latest GMod Tower modules at http://www.gmodtower.org/index.php?p=downloads")

GTowerLangush.AddWord( 2, "empty_bottle",		"Bouteille Vide")
GTowerLangush.AddWord( 2, "empty_bottle_desc",		"Contains absolutely nothing.  Or does it?  You can't be sure until you break it open.")
GTowerLangush.AddWord( 2, "alcohol_bottle",		"Bottle of Alcohol")
GTowerLangush.AddWord( 2, "alcohol_bottle_desc",	"This bottle contains alcohol. Handle with care.")

GTowerLangush.AddWord( 2, "send_trade_request",		"Your trade request has been sent to {1}.")
GTowerLangush.AddWord( 2, "send_trade_recive",		"{1} wants to trade with you.")
GTowerLangush.AddWord( 2, "send_trade_declined",	"{1} has declined your trade.")
GTowerLangush.AddWord( 2, "send_trade_timeout",		"{1} did not respond to your trade.")
GTowerLangush.AddWord( 2, "trade_friend_accept",	"{1}'s acceptance.")

GTowerLangush.AddWord( 2, "send_trade_cancel",	"{1} has cancelled the trade.")
GTowerLangush.AddWord( 2, "trade_succeful",	"Echange effectué avec succès.")

GTowerLangush.AddWord( 2, "trade_you_space",	"You do not have enough space in your inventory - trade failed." )
GTowerLangush.AddWord( 2, "trade_him_space",	"{1} does not have enough space in their inventory - trade failed.")


GTowerLangush.AddWord( 2, "trade_has_accepted",		"{1} accepted." )
GTowerLangush.AddWord( 2, "trade_hasnot_accepted" ,	"{1} has not accepted.")
GTowerLangush.AddWord( 2, "trade_trading_with" ,	"Trading with {1}...")
GTowerLangush.AddWord( 2, "trade_alredy_trading",	"{1} is currently trading." )
GTowerLangush.AddWord( 2, "trade_IamAlredyTrading",	"You are currently trading." )


GTowerLangush.AddWord( 2, "trade_denied",	"Trading is not allowed here.")
GTowerLangush.AddWord( 2, "not_enough_money",	"You do not have enough money.")

GTowerLangush.AddWord( 2, "Playerlist",	"Liste Joueurs")

GTowerLangush.AddWord( 2, "vacant",		"Innocupé")
GTowerLangush.AddWord( 2, "RoomRoomsAvailable",	"Bienvenue, {1}.  Nous avons actuellement <font=Gtowerbigbold>{2}</font> suites de disponibles.   Voulez-vous en réservez une ?")
GTowerLangush.AddWord( 2, "RoomNotAvailable",	"Salutations, {1}.  Nous sommes désolés, il n'y a aucune suite de disponible actuellement. Revenez s'il vous plaît plus tard.")
GTowerLangush.AddWord( 2, "RoomWait",		"Please wait while I setup your suite.")

GTowerLangush.AddWord( 2, "RoomLongAway",	"Vous étiez loin de votre suite pendant {1} minute(s). Vous avez été expulsé.")

GTowerLangush.AddWord( 2, "RoomGet",		"Merci d'avoir choisi notre hôtel.\nJe vous assigne la suite numéro <font=Gtowerbigbold><color=white>#{1}</color></font>.\nSi vous avez besoin d'une assistance avec votre suite, contactez s'il vous plaît un administrateur ou un modérateur. Parlez-moi quand vous voudrez partir de votre suite.")
GTowerLangush.AddWord( 2, "RoomGetSmall",	"Vous avez été assigné à la suite numéro #{1}.")
GTowerLangush.AddWord( 2, "RoomDeny",		"Alright.  Please come back later.")

GTowerLangush.AddWord( 2, "RoomReturn",		"Bonjour, {1}, \nQue puis-je faire pour vous?")
GTowerLangush.AddWord( 2, "RoomReturnYes",	"J’espère que vous avez apprécié votre séjour à l'hôtel.  S’il vous plaît pensez à revenir plus tard.")
GTowerLangush.AddWord( 2, "RoomReturnNo",	"Alright.  I'm glad you're enjoying your suite.  Please talk to me when you wish to check-out.")
GTowerLangush.AddWord( 2, "RoomCleanUp",	"This will reset the suite to its original form.  All purchased furniture items will be deposited in the trunk.")

GTowerLangush.AddWord( 2, "RoomUpgrade",		"Upgrade your suite.")
GTowerLangush.AddWord( 2, "RoomDoWantUpgrade",		"Do you wish to upgrade {1} to level {2}?")
GTowerLangush.AddWord( 2, "RoomNotEnoughMoney",		"You do not have enough money to upgrade {1}.")
GTowerLangush.AddWord( 2, "RoomInventoryOwnRoom",	"You are only allowed to use this in your own suite.")
GTowerLangush.AddWord( 2, "RoomKickPlayers",	"Kick Players")

GTowerLangush.AddWord( 2, "RoomNotOwner",	"Ce n'est pas votre suite.")
GTowerLangush.AddWord( 2, "RoomCheckedOut",	"Vous avez été expulsé de votre suite.")
GTowerLangush.AddWord( 2, "RoomAdminDisabled",	"Admins have disabled your ability to have a suite.")
GTowerLangush.AddWord( 2, "RoomAdminRemoved",	"An admin has removed you from your suite.")
GTowerLangush.AddWord( 2, "RoomMaxEnts",	"Vous ne pouvez pas avoir plus de {1} entités dans votre suite..")

GTowerLangush.AddWord( 2, "RoomOwnerBroke",		"You aren't the suite owner or GTowerRooms broke.")
GTowerLangush.AddWord( 2, "RoomRadioWrongID",	"Radio's suite ID is {1}.  You have {2}.")

GTowerLangush.AddWord( 2, "Scoreboard_awards",		"Succès")

GTowerLangush.AddWord( 2, "Group_menu",			"Group")
GTowerLangush.AddWord( 2, "Group_makeowner",		"Set as Group Leader")
GTowerLangush.AddWord( 2, "Group_removegroup",		"Kick from Group")
GTowerLangush.AddWord( 2, "Group_inviteroup",		"Invite to Group")
GTowerLangush.AddWord( 2, "Group_newownermakesure",	"Are you sure you want to set {1} as the group leader?")
GTowerLangush.AddWord( 2, "Group_younewowner",		"You are now the leader of the group.")
GTowerLangush.AddWord( 2, "Group_himnewowner",		"{1} is now the leader of the group.")

GTowerLangush.AddWord( 2, "GroupInvite",		"{1} has invited you to their group.")
GTowerLangush.AddWord( 2, "GroupDeny",		"{1} has denied your request.")
GTowerLangush.AddWord( 2, "Group_target_no_group",	"{1} is no longer in a group.")
GTowerLangush.AddWord( 2, "Group_full",			"The group is full.")
GTowerLangush.AddWord( 2, "Group_already_in_group",	"You are already in a group.")
GTowerLangush.AddWord( 2, "Group_he_already_in_group",	"{1} is already in a group.")
GTowerLangush.AddWord( 2, "Group_invite_send",		"You have asked {1} to join your group.")
GTowerLangush.AddWord( 2, "Group_leave",		"Leave Group")
GTowerLangush.AddWord( 2, "Group_leavesure",		"Are you sure you want to leave your group?")


GTowerLangush.AddWord( 2, "Group_setting_sizename",		"Size of group health bars.")
GTowerLangush.AddWord( 2, "Group_setting_bordername",		"Distance between each group members' name.")
GTowerLangush.AddWord( 2, "Group_setting_alignname",		"List group vertically.")
GTowerLangush.AddWord( 2, "Group_setting_positionname",		"Posistion of group list.")
GTowerLangush.AddWord( 2, "Group_setting_avatarsizename",	"Group member avatar size.")
GTowerLangush.AddWord( 2, "Group_setting_allbordername",	"Distance from edge of screen.")


GTowerLangush.AddWord( 2, "gui_setting_name",		"Health/Ammo Bar")
GTowerLangush.AddWord( 2, "gui_setting_ammosize",	"Ammo bar size.")
GTowerLangush.AddWord( 2, "gui_setting_ammox",		"Ammo horizontal offset.")
GTowerLangush.AddWord( 2, "gui_setting_ammoy",		"Ammo vertical offset.")
GTowerLangush.AddWord( 2, "gui_setting_healthx",	"Health hortizontal offset.")
GTowerLangush.AddWord( 2, "gui_setting_healthy",	"Health vertical offset.")
GTowerLangush.AddWord( 2, "gui_setting_chatwidth",	"Chat box width.")
GTowerLangush.AddWord( 2, "gui_setting_instant",	"Instant GUI animation transitions.")

GTowerLangush.AddWord( 2, "RadioTurnedOff",		"Radio Off")
GTowerLangush.AddWord( 2, "RadioPlaying",		"Playing")
GTowerLangush.AddWord( 2, "RadioLoading",		"Loading...")
GTowerLangush.AddWord( 2, "RadioUnsupportedFormat",	"Stream using bad format.")
GTowerLangush.AddWord( 2, "RadioTimeout",		"Stream timed out.")
GTowerLangush.AddWord( 2, "RadioBASSInitError",		"BASS initialization error; reconnect.")
GTowerLangush.AddWord( 2, "RadioUnknown",		"Stream gave unknown error.")

GTowerLangush.AddWord( 2, "JukeBoxTurnedOff",		"Jukebox Off (5 GMC per choice)")
GTowerLangush.AddWord( 2, "JukeBoxNotEnoughMoney",	"You cannot afford to change the jukebox.")

GTowerLangush.AddWord( 2, "MenuReportAdmin",	"Report to Admin")
GTowerLangush.AddWord( 2, "MenuInformation",	"Information")
GTowerLangush.AddWord( 2, "MenuTrade",		"Trade")

GTowerLangush.AddWord( 2, "StoreNoSlots",	"You do not have enough inventory slots.")
GTowerLangush.AddWord( 2, "StoreNotEnoughMoney",	"You cannot afford this item.")
GTowerLangush.AddWord( 2, "StorePurchased",	"You've just bought ''{1}''.")
GTowerLangush.AddWord( 2, "StoreConfirmUpgrade",	"Are you sure you want to upgrade the ''{1}'' for {2} GMC?")
GTowerLangush.AddWord( 2, "StoreConfirmPurchase",	"Are you sure you want to buy ''{1}'' for {2} GMC?")

GTowerLangush.AddWord( 2, "BankFull",	"There isn't enough space in your bank.")
GTowerLangush.AddWord( 2, "InventoryTooFar",	"It's too far away.")

GTowerLangush.AddWord( 2, "BackpackShouldEquip",	"You should equip backpack before using it.")

GTowerLangush.AddWord( 2, "AchievementsGot",	"Congratulations! You've just achieved: {1}.")
GTowerLangush.AddWord( 2, "AchievementsTrophyGot",	"You got the {1}.")
GTowerLangush.AddWord( 2, "AchievementsTrophyFailed",	"Oops, a mistake was made.")

GTowerLangush.AddWord( 2, "MoneyEarned",	"You've earned {1} GMC.")
GTowerLangush.AddWord( 2, "MoneySpent",	"You've spent {1} GMC.")

GTowerLangush.AddWord( 2, "GamemodeFull",	"Sorry, {1} is full.")

GTowerLangush.AddWord( 2, "AdminNot",	"You are not an admin!")
GTowerLangush.AddWord( 2, "AfkTimer",	"AFK TIMER: {1} seconds.")

GTowerLangush.AddWord( 2, "PlayerModel",	"Player Model")
GTowerLangush.AddWord( 2, "MissingTrophies",	"Missing Trophies?")
GTowerLangush.AddWord( 2, "Theater",	"Theater")

GTowerLangush.AddWord( 2, "EventMiniStart",	"Event System has started minigame: {1}.")
GTowerLangush.AddWord( 2, "EventMiniEnd",	"Event System has ended minigame: {1}.")
GTowerLangush.AddWord( 2, "EventSetSale",	"Event System has set the {1} on sale!")
GTowerLangush.AddWord( 2, "EventEndSale",	"Event System has ended the sale on the {1}.")
GTowerLangush.AddWord( 2, "EventError",		"Something is terribly wrong with event system! Tell an admin about this!")
GTowerLangush.AddWord( 2, "EventEndingTime", "Event will end in {1}!")
GTowerLangush.AddWord( 2, "EventNextEventTime", "Be ready, we have random events every half an hour!")
GTowerLangush.AddWord( 2, "EventNoEvent", "Sorry, there will be no event!")
GTowerLangush.AddWord( 2, "EventNeedMorePlayers", "Event skipped, need more players (10)!")
GTowerLangush.AddWord( 2, "EventAdminDisabled", "An admin ({1}) has disabled event system.")
GTowerLangush.AddWord( 2, "EventAdminEnabled", "An admin ({1}) has enabled event system.")
GTowerLangush.AddWord( 2, "EventAdminManual", "An admin ({1}) has forced event system.")

GTowerLangush.AddWord( 2, "AuctionStarted", "Auction started! Place a bet like this: !bet 5000")
GTowerLangush.AddWord( 2, "AuctionCurrentBet", "Current bet: {1} GMC by {2}")
GTowerLangush.AddWord( 2, "AuctionStartedItem", "New lot: {1}. Starting price: {2}. Please check if you have free space in inventory before joining.")
GTowerLangush.AddWord( 2, "AuctionSold", "{1} sold to {2} for {3} GMC!")
GTowerLangush.AddWord( 2, "AuctionEnded", "Auction ended!")
GTowerLangush.AddWord( 2, "AuctionNoInventorySpace", "{1} don't have space in inventory! He gets 50% of {2} price!")

GTowerLangush.AddWord( 2, "AdminMiniStart",	"An admin ({1}) has started minigame: {2}.")
GTowerLangush.AddWord( 2, "AdminMiniEnd",	"An admin ({1}) has ended minigame: {2}.")
GTowerLangush.AddWord( 2, "AdminClrDecals",	"An admin ({1}) has cleared all decals.")
GTowerLangush.AddWord( 2, "AdminClrSounds",	"An admin ({1}) has stopped all sounds.")
GTowerLangush.AddWord( 2, "AdminClrStreams", "An admin ({1}) has removed all streams.")
GTowerLangush.AddWord( 2, "AdminSetSale",	"An admin ({1}) has set the {2} on sale!")
GTowerLangush.AddWord( 2, "AdminEndSale",	"An admin ({1}) has ended the sale on the {2}.")
GTowerLangush.AddWord( 2, "AdminRagdoll",	"An admin or privadmin ({1}) has ragdolled you!")
GTowerLangush.AddWord( 2, "AdminRagdollA",	"You've ragdolled {1}!")
GTowerLangush.AddWord( 2, "AdminSetMoney",	"An admin ({1}) has set your money to {2}.")

GTowerLangush.AddWord( 2, "TODO", "TODO")
GTowerLangush.AddWord( 2, "Gamemode Ports", "Gamemode Ports" )
GTowerLangush.AddWord( 2, "Entertainment Plaza", "Entertainment Plaza")
GTowerLangush.AddWord( 2, "Suite Floor", "Suite Floor" )
GTowerLangush.AddWord( 2, "Suites 1-5", "Suites 1-5" )
GTowerLangush.AddWord( 2, "Suites 6-10", "Suites 6-10" )
GTowerLangush.AddWord( 2, "Arcade", "Arcade" )
GTowerLangush.AddWord( 2, "Teleporters", "Teleporters")
GTowerLangush.AddWord( 2, "Dev. HQ", "Dev. HQ" )
GTowerLangush.AddWord( 2, "Resturant", "Resturant")
GTowerLangush.AddWord( 2, "Ball Race", "Ball Race" )
GTowerLangush.AddWord( 2, "Action Genre", "Action Genre")
GTowerLangush.AddWord( 2, "PVP Battle", "PVP Battle" )
GTowerLangush.AddWord( 2, "Stealth - Coming Soon", "Stealth - Coming Soon" )
GTowerLangush.AddWord( 2, "Coming Soon", "Coming Soon" )
GTowerLangush.AddWord( 2, "GMT: Adventure", "GMT: Adventure" )
GTowerLangush.AddWord( 2, "Stealth", "Stealth" )
GTowerLangush.AddWord( 2, "Puzzle: Impossible", "Puzzle: Impossible" )
GTowerLangush.AddWord( 2, "Tetris", "Tetris" )
GTowerLangush.AddWord( 2, "Bar", "Bar" )
GTowerLangush.AddWord( 2, "Theatre", "Theatre" )
GTowerLangush.AddWord( 2, "Party Suite", "Party Suite" )
GTowerLangush.AddWord( 2, "The Gallery", "The Gallery" )
GTowerLangush.AddWord( 2, "Twist of the Mind", "Twist of the Mind" )
GTowerLangush.AddWord( 2, "Mini-Golf", "Mini-Golf" )
GTowerLangush.AddWord( 2, "Monotone", "Monotone" )
GTowerLangush.AddWord( 2, "Harvest", "Harvest") 
GTowerLangush.AddWord( 2, "Furniture Store", "Furniture Store" )
GTowerLangush.AddWord( 2, "Hat Store", "Hat Store" )
GTowerLangush.AddWord( 2, "Souvenir Store", "Souvenir Store" )
GTowerLangush.AddWord( 2, "Electronic Store", "Electronic Store" )
GTowerLangush.AddWord( 2, "Conquest", "Conquest" )
GTowerLangush.AddWord( 2, "Chainsaw Battle!","Chainsaw Battle!")
GTowerLangush.AddWord( 2, "Blizzard Storm!", "Blizzard Storm!" )
